cadastros/urls.py
from django.urls import path

from .views import GeneroCreate, GeneroLista, GeneroUpdate, HomeView
from .views import IdiomaCreate, IdiomaLista, IdiomaUpdate
from .views import AutorCreate, AutorLista, AutorUpdate
from .views import UsuarioCreate, UsuarioLista, UsuarioUpdate
from .views import LivroCreate, LivroLista, LivroUpdate
from .views import EmprestimoCreate, EmprestimoLista, EmprestimoUpdate, EmprestimoDetailsView
from .views import ReservaCreate, ReservaLista, ReservaUpdate, pie_chart

urlpatterns = [
    path('',HomeView.as_view(),name='index'),
    path('index/',HomeView.as_view(),name='index'),
]    
urlpatterns += [        
    #Gênero
    path('cadastrar/genero',GeneroCreate.as_view(), name='cadastrar-genero'),
    path('editar/genero/<int:pk>/',GeneroUpdate.as_view(), name='editar-genero'),        
    path('listas/formListarGenero/', GeneroLista.as_view(),name="listar-genero"),
]
urlpatterns += [    
    #Idioma
    path('cadastrar/idioma',IdiomaCreate.as_view(), name='cadastrar-idioma'),
    path('editar/idioma/<int:pk>/',IdiomaUpdate.as_view(), name='editar-idioma'),        
    path('listas/formListarIdioma/', IdiomaLista.as_view(),name="listar-idioma"),
]
urlpatterns += [    
    #Autor
    path('cadastrar/autor',AutorCreate.as_view(), name='cadastrar-autor'),
    path('editar/autor/<int:pk>/',AutorUpdate.as_view(), name='editar-autor'),        
    path('listas/formListarAutor/', AutorLista.as_view(),name="listar-autor"),
]
urlpatterns += [    
    #Usuário
    path('cadastrar/usuario',UsuarioCreate.as_view(), name='cadastrar-usuario'),
    path('editar/usuario/<int:pk>/',UsuarioUpdate.as_view(), name='editar-usuario'),        
    path('listas/formListarUsuario/', UsuarioLista.as_view(),name="listar-usuario"),    
]
urlpatterns += [    
    #Livro
    path('cadastrar/livro',LivroCreate.as_view(), name='cadastrar-livro'),
    path('editar/livro/<int:pk>/',LivroUpdate.as_view(), name='editar-livro'),        
    path('listas/formListarLivro/', LivroLista.as_view(),name="listar-livro"),
]    
urlpatterns += [    
    #Emprestimo
    path('cadastrar/emprestimo',EmprestimoCreate.as_view(), name='cadastrar-emprestimo'),
    path('editar/emprestimo/<uuid:pk>/',EmprestimoUpdate.as_view(), name='editar-emprestimo'),        
    path('listas/formListarEmprestimo/', EmprestimoLista.as_view(),name="listar-emprestimo"),
    path('emprestimo/<uuid:pk>/detalhes/',EmprestimoDetailsView.as_view(),name='emprestimo-detalhes'),
]      
urlpatterns += [    
    #Reserva
    path('cadastrar/reserva',ReservaCreate.as_view(), name='cadastrar-reserva'),
    path('editar/reserva/<int:pk>/',ReservaUpdate.as_view(), name='editar-reserva'),        
    path('listas/formListarReserva/', ReservaLista.as_view(),name="listar-reserva"),
]      
urlpatterns+=[
    path('get/ajax/QtdeEstoque', EmprestimoCreate.pegaEstoqueLivro, name = "pegaEstoque")
]
#Grafico
urlpatterns+=[
    path('livro-chart/',pie_chart, name='livro-chart'), 
]   

paginas/urls.py
from django.urls import path # importando da lib
from .views import PaginaInicial, SobreView # importando do arquivo views.py

urlpatterns = [
    # padrão é path('endereco/', minhaview.as_view(),name='nome da url')
    #path('',PaginaInicial.as_view(),name='index'),
    #path('index/',PaginaInicial.as_view(),name='index'),
    path('sobre/', SobreView.as_view(),name='sobre'),
]

cadastros/models.py
import datetime
from django.db import models
from django.db.models.deletion import CASCADE, RESTRICT
from django.db.models.fields import AutoField
from django.contrib.auth.models import Group, User
from django.urls import reverse
import uuid 
from datetime import date, timedelta

# Create your models here.

def user_path(instance, filename):
    return "Usuário {0}/{1}".format(instance.user.id, filename)

class Usuario(models.Model):
    SEXO_CHOICES = [
        ["F", "Feminino"],
        ["M", "Masculino"],
        ["N", "Nenhuma das opções"]
    ]

    STATE_CHOICES = [
        ['AC', 'Acre'], 
        ['AL', 'Alagoas'], 
        ['AP', 'Amapá'],
        ['AM', 'Amazonas'],
        ['BA', 'Bahia'],
        ['CE', 'Ceará'],
        ['DF', 'Distrito Federal'],
        ['ES', 'Espírito Santo'],
        ['GO', 'Goiás'],
        ['MA', 'Maranhão'],
        ['MT', 'Mato Grosso'],
        ['MS', 'Mato Grosso do Sul'],
        ['MG', 'Minas Gerais'],
        ['PA', 'Pará'],
        ['PB', 'Paraíba'],
        ['PR', 'Paraná'],
        ['PE', 'Pernambuco'],
        ['PI', 'Piauí'],
        ['RJ', 'Rio de Janeiro'],
        ['RN', 'Rio Grande do Norte'],
        ['RS', 'Rio Grande do Sul'],
        ['RO', 'Rondônia'],
        ['RR', 'Roraima'],
        ['SC', 'Santa Catarina'],
        ['SP', 'São Paulo'],
        ['SE', 'Sergipe'],
        ['TO', 'Tocantins']
    ]
    
    usuarioID = models.BigAutoField(primary_key=True)
    rg = models.BigIntegerField(unique=True,verbose_name= 'RG')
    nome = models.CharField(max_length=255,verbose_name= 'Nome')   
    sobrenome = models.CharField(max_length=255,verbose_name= 'Sobrenome')   
    nascimento = models.DateField(blank=True, null=True,verbose_name='Data de Nascimento')
    sexo = models.CharField(null=True,max_length=1,choices=SEXO_CHOICES,verbose_name='Sexo')
    telefone = models.CharField(max_length=15 ,blank=True, null = True, verbose_name= 'Telefone')
    celular = models.CharField(max_length=15, blank=True, null = True, verbose_name= 'Celular')
    email1 = models.EmailField(max_length=255, blank=True, null = True, verbose_name= 'Email Principal')
    email2 = models.EmailField(max_length=255,  blank=True, null = True, verbose_name= 'Email Alternativo')
    cep = models.CharField(max_length=9,verbose_name= 'C.E.P.')
    endereco = models.CharField(max_length=255,verbose_name= 'Endereço')
    numero = models.CharField(max_length=6,verbose_name= 'Número')
    bairro = models.CharField(max_length=100,verbose_name= 'Bairro')
    municipio = models.CharField(max_length=50,verbose_name= 'Município')
    estado = models.CharField(max_length=2,choices=STATE_CHOICES,verbose_name='UF')
    serie = models.CharField(blank=True, max_length=50,null=True,verbose_name= 'Série')    
    is_active = models.BooleanField(default=True,verbose_name= '', help_text='Marque para Ativar/Desmarque para Desativar o usuário')
    createdAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Criação')
    updatedAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Modificação')
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT,verbose_name="Usuário Sistema")
    grupo = models.ForeignKey(Group,on_delete=models.RESTRICT, verbose_name="Grupo")
    
    def __str__(self):
        return "{}".format(self.nome)

    class Meta:
        db_table='Usuario'
        
class Genero(models.Model):
    """Model que representa um gênero de um livro (exemplo. Ficção, Tecnologia)."""
    generoID = models.BigAutoField(primary_key=True)
    nome = models.CharField(unique=True,max_length=200,verbose_name="Nome",help_text="Informe um gênero de livro (exemplo. Ficção, Tecnologia)")
    descricao = models.TextField(verbose_name= 'Descrição',help_text="Digite uma descrição do gênero")
    is_active = models.BooleanField(default=True,verbose_name= '', help_text='Marque para Ativar/Desmarque para Desativar o gênero')
    createdAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Criação')
    updatedAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Modificação')
    def __str__(self):        
        return self.nome
    class Meta:
        db_table='Genero'
    
class Idioma(models.Model):
    """Model que representa a linguagem do livro (exemplo Inglês, Português, etc.)"""
    idiomaID = models.BigAutoField(primary_key=True)
    nome = models.CharField(unique=True,verbose_name="Nome",max_length=100,help_text="Informe o idioma do livro (exemplo. Inglês, Português etc.)")
    is_active = models.BooleanField(default=True,verbose_name= '', help_text="Marque para Ativar/Desmarque para Desativar o idioma")
    createdAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Criação')
    updatedAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Modificação')

    def __str__(self):
        return self.nome
    class Meta:
        db_table='Idioma'

class Autor(models.Model):
    """Model que representa o autor."""
    autorID = models.BigAutoField(primary_key=True)
    nome = models.CharField(max_length=100,verbose_name="Nome",help_text="Informe o nome do autor")
    sobrenome = models.CharField(max_length=100, verbose_name="Sobrenome",help_text="Informe o sobrenome do autor")
    dataNascimento = models.DateField(null=True, blank=True, verbose_name="Data de Nascimento",help_text="Informe a data de nascimento do autor")
    dataFalecimento = models.DateField(null=True, blank=True,verbose_name="Data de Falecimento")
    is_active = models.BooleanField(default=True,verbose_name= '', help_text="Marque para Ativar/Desmarque para Desativar o autor")
    createdAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Criação')
    updatedAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Modificação')

    class Meta:
        ordering = ['sobrenome', 'nome']
        db_table='Autor'
    

    def get_absolute_url(self):
        """Retorna a url para acessar o autor."""
        return reverse('autor-detalhes', args=[str(self.id)])

    def __str__(self):        
        return '{0}, {1}'.format(self.sobrenome, self.nome)


class Livro(models.Model):
    livroID = models.BigAutoField(primary_key=True)
    titulo = models.CharField(unique=True,max_length = 100,help_text="Informe o título do Livro", verbose_name= 'Título')
    autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True, help_text="Selecione um autor para o livro",verbose_name="Autor")
    co_autor = models.CharField(max_length = 50, blank = True,verbose_name= 'COAUTOR',help_text="Informe o coautor do livro")
    sumario = models.TextField(max_length=1000, help_text="Informe uma breve descrição do livro",verbose_name="Sumário")
    isbn = models.CharField('ISBN', max_length=13,
                            unique=True,                            
                            help_text='13 Caracteres no máximo <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN número</a>')
    genero = models.ForeignKey('Genero', on_delete=models.SET_NULL, null=True, verbose_name="Gênero",help_text="Selecione um gênero para o livro")
    idioma = models.ForeignKey('Idioma', on_delete=models.SET_NULL, null=True,verbose_name="Idioma",help_text="Selecione o idioma do livro")
    quantidade = models.IntegerField(verbose_name='Qtde.',help_text="Informe a Quantidade de livros")
    is_active = models.BooleanField(default=True,verbose_name= '', help_text="Marque para Ativar/Desmarque para Desativar o livro")
    createdAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Criação')
    updatedAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Modificação')
   
    class Meta:
        verbose_name = 'Livro'
        db_table='Livro'
        ordering = ['titulo', 'autor']

    def display_genero(self):
        """Cria uma string para o gênero"""
        return ', '.join([genero.nome for genero in self.genero.all()[:3]])

    display_genero.short_description = 'Gênero'

    def get_absolute_url(self):
        """Retorna a url para acessar os detalhes do livro."""
        return reverse('livro-detalhe', args=[str(self.id)])

    def __str__(self):        
        return self.titulo

class Reserva(models.Model):
    reservaID = models.BigAutoField(primary_key=True)
    livro = models.ForeignKey('Livro', on_delete=models.RESTRICT, null=True,help_text="Selecione o livro a reservar")
    nomeSolicitante = models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True, blank=True,verbose_name="Usuário",help_text="Selecione o nome do usuário")
    is_active = models.BooleanField(default=True,verbose_name= '', help_text="Marque para Ativar/Desmarque para Cancelar a reserva")    
    dataReserva = models.DateField(default = date.today, verbose_name="Data da Reserva",help_text="Informe a data da reserva do livro")
    createdAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Criação')
    updatedAt = models.DateTimeField(auto_now=True, verbose_name= 'Data de Modificação')
    class Meta:
        verbose_name = 'Reserva'
        db_table='Reserva'
        ordering = ['createdAt']


class Emprestimo(models.Model):   
    dataDevolucaotemp =  date.today()    
    dataDevolucaotemp += timedelta(days = 7)

    choices = (
        ('P', 'Péssimo'),
        ('R', 'Ruim'),
        ('B', 'Bom'),
        ('O', 'Ótimo')
    )
    emprestimoID = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="ID particular para esse livro")
    livro = models.ForeignKey('Livro', on_delete=models.RESTRICT, null=True,help_text="Selecione o livro a emprestar")
    marca = models.CharField(max_length=200)
    usuario = models.ForeignKey(Usuario, on_delete=models.SET_NULL, null=True, blank=True,verbose_name="Usuário",help_text="Selecione o nome do usuário")

paginas/models.py
from django.db import models

# Create your models here.

paginas/views.py
#from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class PaginaInicial(TemplateView):
    template_name = "/base/index.html"

class SobreView(TemplateView):
    template_name = "sobre.html"    

paginas/templates/cadastros/formCadastroAutor.html
{% extends 'base/modelo.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<div class="card text-dark bg-light mb-3">
    <h2 class="card-header text-center">
        Cadastro do Autor
    </h2>
    <div class="card-body">
        <h3 class="card-title lead text-danger">* Preencha todos os campos obrigatórios.</h3>
        <hr>
        <form  action="" method="POST">
            {% csrf_token %}
            <div class="row mb-2"> 
                <div class="col-md-12">
                    {{ form.nome|as_crispy_field }}
                </div>            
                <div class="col-md-12">
                    {{ form.sobrenome|as_crispy_field }}
                </div>  
                <div class="col-md-6">
                    {{ form.dataNascimento|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.dataFalecimento|as_crispy_field }}
                </div>
                <div class="col-md-4 d-flex align-items-end">
                    {{ form.is_active|as_crispy_field }}      
                </div>
            </div>

            <div class="card-footer text-muted">  
                <div class="btn-group">
                    <button type="submit" class="btn btn-success mt-1 mx-1" title = "Salvar">        
                        <i class="fa fa-check" aria-hidden="true"></i>
                        Gravar
                    </button>
                    <button type="reset" class="btn btn-warning mt-1 mx-1" title = "Limpar">        
                        <i class="fa fa-eraser" aria-hidden="true"></i>
                        Limpar
                    </button>
                    <a class="btn btn-secondary mt-1 mx-1" title = "Voltar" href="{{ link }}">           
                        <i class="fas fa-door-closed"></i>
                        Voltar
                    </a>
                </div>
            </div>    
        </form>
    </div>
</div>        
{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>
    $(document).ready(function(){
        $('#id_dataNascimento').mask('00/00/0000', {placeholder: "__/__/____"});
        $('#id_dataFalecimento').mask('00/00/0000', {placeholder: "__/__/____"});
       
    });
</script>
{% endblock %}

paginas/templates/cadastros/formCadastroEmprestimo.html
{% extends 'base/modelo.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<div class="card text-dark bg-light mb-3">
    <h2 class="card-header text-center">
        Cadastro do Empréstimo
    </h2>
    <div class="card-body">
        <h3 class="card-title lead text-danger">* Preencha todos os campos obrigatórios.</h3>
        <hr>
        <form  action="" method="POST">
            {% csrf_token %}
            <!-- form|crispy -->            
            <div class="row"> 
                <small id="estoque"></small>
                <div class="col-md-4">
                    {{ form.livro|as_crispy_field }}                    
                </div>
                <div class="col-md-4">
                    {{ form.marca|as_crispy_field }}
                </div>
                <div class="col-md-2">
                    {{ form.usuario|as_crispy_field }}      
                </div>        
            </div>
            <div class="row">         
                <div class="col-md-3">
                    {{ form.dataEmprestimo|as_crispy_field }}      
                </div>            
                <div class="col-md-3">
                    {{ form.dataPrazoDevolucao|as_crispy_field }}      
                </div>
            </div>    
            <div class="row">         
                <hr/>
                <h5 class="card-header text-center">
                    Devolução
                </h5>
                
                <div class="col-md-3">
                    {{ form.dataDevolucao|as_crispy_field }}      
                </div>
                <div class="col-md-3">
                    {{ form.avaliacao|as_crispy_field }}      
                </div>
            </div>
            <div class="row mb-2">    
                <div class="col-md-4 d-flex align-items-end">
                    {{ form.is_active|as_crispy_field }}      
                </div>
            </div>

            <div class="card-footer text-muted">  
                <div class="btn-group">
                    <button id="btnemprestar" type="submit" class="btn btn-success mt-13 mx-1" title = "Salvar">        
                        <i class="fa fa-check" aria-hidden="true"></i>
                        Gravar
                    </button>
                    <button type="reset" class="btn btn-warning mt-1 mx-1" title = "Limpar">        
                        <i class="fa fa-eraser" aria-hidden="true"></i>
                        Limpar
                    </button>
                    <a class="btn btn-secondary mt-1 mx-1" title = "Voltar" href="{{ link }}">           
                        <i class="fas fa-door-closed"></i>
                        Voltar
                    </a>
                </div>
            </div> 
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script>
$(document).ready(function(){
    $('#id_sumario').attr('rows','5');
    $('#id_dataEmprestimo,#id_dataDevolucao,#id_dataPrazoDevolucao').mask('00/00/0000', {placeholder: "__/__/____"});
    $('#id_dataEmprestimo,#id_dataPrazoDevolucao').attr('readonly', true);

    $("#id_livro").change(function() {
        $('#estoque').html("");
        var livroid = $(this).val();
        if(isNaN(livroid) || livroid == ''){
            return;
        }                    
        $.ajax({
            type: 'GET',
            url: "{% url 'pegaEstoque' %}",
            data: {"livroid": livroid},
            success: function (response) {                
                if(response["qtdeestoque"] > 0){                    
                    $('#estoque').append('<div class="badge bg-success">Quantidade disponível '+response["qtdeestoque"]+'</div>');    
                    $('#btnemprestar').prop('disabled', false);    
                }else{
                    alert("Livro Indisponível no momento");
                    $('#estoque').append('<div class="badge bg-danger">Livro indisponível no momento - Qtde. '+response["qtdeestoque"]+'</div>');    
                    $('#btnemprestar').prop('disabled', true);    
                }
            },
            error: function (jqXHR, textStatus,errorThrown ) {
                alert(errorThrown);
            }
        })
     }); 
})    
</script>
{% endblock %}

paginas/templates/cadastros/formCadastroGenero.html
{% extends 'base/modelo.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<div class="card text-dark bg-light mb-3">
    <h2 class="card-header text-center">
        Cadastro do Gênero
    </h2>
    <div class="card-body">
        <h3 class="card-title lead text-danger">* Preencha todos os campos obrigatórios.</h3>
        <hr>
        <form  action="" method="POST">
            {% csrf_token %}
            <div class="row mb-2"> 
                <div class="col-md-12">
                    {{ form.nome|as_crispy_field }}
                </div>            
                <div class="col-md-12">
                    {{ form.descricao|as_crispy_field }}
                </div>
                <div class="col-md-4 d-flex align-items-end">
                    {{ form.is_active|as_crispy_field }}      
                </div>
            </div>

            <div class="card-footer text-muted">  
                <div class="btn-group">
                    <button type="submit" class="btn btn-success mt-1 mx-1" title = "Salvar">        
                        <i class="fa fa-check" aria-hidden="true"></i>
                        Gravar
                    </button>
                    <button type="reset" class="btn btn-warning mt-1 mx-1" title = "Limpar">        
                        <i class="fa fa-eraser" aria-hidden="true"></i>
                        Limpar
                    </button>
                    <a class="btn btn-secondary mt-1 mx-1" title = "Voltar" href="{{ link }}">           
                        <i class="fas fa-door-closed"></i>
                        Voltar
                    </a>
                </div>
            </div>    
        </form>
    </div>
</div>        
{% endblock %}

{% block scripts %}

{% endblock %}

paginas/templates/cadastros/formCadastroLivro.html
{% extends 'base/modelo.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<div class="card text-dark bg-light mb-3">
    <h2 class="card-header text-center">
        Cadastro do Livro
    </h2>
    <div class="card-body">
        <h3 class="card-title lead text-danger">* Preencha todos os campos obrigatórios.</h3>
        <hr>
        <form  action="" method="POST">
            {% csrf_token %}
            <!-- form|crispy -->
            <div class="row"> 
                <div class="col-md-4">
                    {{ form.titulo|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.autor|as_crispy_field }}
                </div>
                <div class="col-md-2">
                    {{ form.co_autor|as_crispy_field }}      
                </div>
                <div class="col-md-2">
                    {{ form.quantidade|as_crispy_field }}      
                </div>
            </div>    
            <div class="row">    
                <div class="col-md-12">
                    {{ form.sumario|as_crispy_field }}      
                </div>
            </div>    
            <div class="row">    
                <div class="col-md-6">
                    {{ form.isbn|as_crispy_field }}      
                </div>
                <div class="col-md-3">
                    {{ form.genero|as_crispy_field }}      
                </div>
                <div class="col-md-3">
                    {{ form.idioma|as_crispy_field }}      
                </div>
            </div>
            <div class="row mb-2">    
                <div class="col-md-4 d-flex align-items-end">
                    {{ form.is_active|as_crispy_field }}      
                </div>
            </div>

            <div class="card-footer text-muted">  
                <div class="btn-group">
                    <button type="submit" class="btn btn-success mt-13 mx-1" title = "Salvar">        
                        <i class="fa fa-check" aria-hidden="true"></i>
                        Gravar
                    </button>
                    <button type="reset" class="btn btn-warning mt-1 mx-1" title = "Limpar">        
                        <i class="fa fa-eraser" aria-hidden="true"></i>
                        Limpar
                    </button>
                    <a class="btn btn-secondary mt-1 mx-1" title = "Voltar" href="{{ link }}">           
                        <i class="fas fa-door-closed"></i>
                        Voltar
                    </a>
                </div>
            </div> 
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
$(document).ready(function(){
    $('#id_sumario').attr('rows','5');
})    
{% endblock %}

paginas/templates/cadastros/formCadastroUsuario.html
{% extends 'base/modelo.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<div class="card text-dark bg-light mb-3">
    <h2 class="card-header text-center">
        Cadastro do Usuário
    </h2>
    <div class="card-body">
        <h3 class="card-title lead text-danger">* Preencha todos os campos obrigatórios.</h3>
        <hr>
        <form  action="" method="POST">
            {% csrf_token %}
            <!-- form|crispy -->
            <div class="row"> 
                <div class="col-md-4">
                    {{ form.nome|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.sobrenome|as_crispy_field }}
                </div>
                <div class="col-md-2">
                    {{ form.rg|as_crispy_field }}      
                </div>
                <div class="col-md-2">
                    {{ form.nascimento|as_crispy_field }}      
                </div>
                <div class="col-md-2">
                    {{ form.sexo|as_crispy_field }}      
                </div>
                <div class="col-md-2">
                    {{ form.telefone|as_crispy_field }}      
                </div>
                <div class="col-md-2">
                    {{ form.celular|as_crispy_field }}      
                </div>
                <div class="col-md-3">
                    {{ form.email1|as_crispy_field }}      
                </div>
                <div class="col-md-3">
                    {{ form.email2|as_crispy_field }}      
                </div>
                <div class="col-md-6">
                    {{ form.endereco|as_crispy_field }}      
                </div>
                <div class="col-md-2">
                    {{ form.numero|as_crispy_field }}      
                </div>
                <div class="col-md-4">
                    {{ form.bairro|as_crispy_field }}      
                </div>
                <div class="col-md-6">
                    {{ form.municipio|as_crispy_field }}      
                </div>
                    <div class="col-md-3">
                    {{ form.estado|as_crispy_field }}      
                </div>
                <div class="col-md-3">
                    {{ form.cep|as_crispy_field }}      
                </div>
                <div class="col-md-2">
                    {{ form.serie|as_crispy_field }}      
                </div>
                <div class="col-md-2">
                    {{ form.grupo|as_crispy_field }}      
                </div>
                <div class="col-md-2">
                    {{ form.usuario|as_crispy_field }}      
                </div>
            </div>
            <div class="row mb-2">    
                <div class="col-md-4 d-flex align-items-end">
                    {{ form.is_active|as_crispy_field }}      
                </div>
            </div>

            <div class="card-footer text-muted">  
                <div class="btn-group">
                    <button type="submit" class="btn btn-success mt-13 mx-1" title = "Salvar">        
                        <i class="fa fa-check" aria-hidden="true"></i>
                        Gravar
                    </button>
                    <button type="reset" class="btn btn-warning mt-1 mx-1" title = "Limpar">        
                        <i class="fa fa-eraser" aria-hidden="true"></i>
                        Limpar
                    </button>
                    <a class="btn btn-secondary mt-1 mx-1" title = "Voltar" href="{{ link }}">           
                        <i class="fas fa-door-closed"></i>
                        Voltar
                    </a>
                </div>
            </div> 
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>
    $(document).ready(function(){
        $("#id_rg").keypress(function(e) {
           var keyCode = e.which ? e.which : e.keyCode
           if (!(keyCode >= 48 && keyCode <= 57))
               return false;
 
            if(this.value.length > 13)
               return false      
        })  
        $('#id_telefone').mask('(00) 0000-0000');
        $('#id_celular').mask('(00) 00000-0000');
        $('#id_nascimento').mask('00/00/0000', {placeholder: "__/__/____"});
        $('#id_cep').mask('00000-000');
       
    });
</script>
{% endblock %}